### ISSUE TITLE
В success ссылка и форматирование

### ISSUE THREAD

**Issue by imyourdream** [imyourdream/Marmot#12]
- [x] В файле success имя сервера должно быть гиперссылкой до имя_сервера/ASPnetKP
- [x] А теперь нужно сделать так, чтобы редактирование ссылки было доступно из админки и хранилось в базе, то есть в таблицу листсервер нужно добавить еще одно поле - link и автоматически его заполнять (имя_сервера/ASPnetKP) и в момент рендеринга success читать линк из базы и пихать в шаблон (5a76472)

**Comment by Jazzis18** [comment]
@imyourdream что в форматировании подправить? заменить абзацы на маркированный список или ?

**Comment by imyourdream** [comment]
@Jazzis18 Обновил

**Comment by Jazzis18** [comment]
Closed in 5a76472
