### ISSUE TITLE
Не отображается юзер и работает кнопка вызова модалки авторизации

### ISSUE THREAD

**Issue by imyourdream** [imyourdream/Marmot#42]
1. Завершим сессию если открыта и перейдем на home page
2. Логинимся
3. Переходим в db-manager
4. Жмем на кнопку с названием проекта (Marmot в левом верхнем углу контентной части)
5. Получаем редирект на home page, но тут встречаем вместо логина кнопку войти, которая вызывает окно авторизации, при чем сессия активна и вновь нажав на переход в приложение db-manager мы перейдем на страницу этого модуля и тут все будет отображаться корректно.

![image](https://cloud.githubusercontent.com/assets/17480018/20694525/8e91120a-b607-11e6-9ad0-c3b5f4910ac6.png)

**Comment by Jazzis18** [comment]
@imyourdream Исправил.
