### ISSUE TITLE
home_page double enter

### ISSUE THREAD

**Issue by imyourdream** [imyourdream/Marmot#45]
При авторизации после ввода логина и пароля можно быстро нажать enter дважды и тогда после авторизации модальное окно появится заново:
![image](https://cloud.githubusercontent.com/assets/17480018/20747930/d2b0da72-b70d-11e6-9508-5a765e0a061a.png)
Update:
А если очень быстро нажать несколько раз, то модалка появится, экран затемнится, но при закрытии модалки затемнение (блокирующее всю страницу) останется от прошлой модалки, которая была быстро закрыта при открытии новой.

**Comment by Jazzis18** [comment]
@imyourdream "Исправил" (обошёл) путем блока сабмита после её нажатия на время обработки запроса.
- В случае успеха сабмит не разлочивается, происходит перезагрузка страницы.
- В случае неудачи сабмит разлочивается.

**Comment by imyourdream** [comment]
Необходимо так же блочить и другие кнопки в приложении, особенно старт рестора и прочие связанные с основным функционалом модуля. Решение может потребоваться и в будущем так что опиши его здесь.

**Comment by Jazzis18** [comment]
@imyourdream 
```JavaScritp
$(selector).prop('disabled', true);
```
