### ISSUE TITLE
update-asp не авторизованный пользователь может получить верстку другой страницы

### ISSUE THREAD

**Issue by imyourdream** [imyourdream/Marmot#49]
- [ ] При нажатии на кнопку обновить вставляется под таблицу (для теста это путь), но если юзер в этот момент не авторизован, то есть если он открыл вторую страницу и на ней нажал выход, то при нажатии на кнопку "обновить выделенные" он получит верстку с home page через ajax.
![image](https://cloud.githubusercontent.com/assets/17480018/20810723/b29c45a8-b82c-11e6-9739-12d8018cb415.png)
- [ ] Необходимо проверить и другие части проекта на наличие подобных багов.

**Comment by imyourdream** [comment]
Добавлено модальное окно для подтверждения в это модуль, но проблема еще не решена
![image](https://cloud.githubusercontent.com/assets/17480018/20855191/9401a688-b91c-11e6-8afe-b17a6e898d8f.png)

**Comment by Jazzis18** [comment]
исправлено с добавлением прав доступа
